const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    Type: "Apartment",
    Total_Area: "250",
    Built_in_Area: "250",
    State: "Addis Ababa",
    City: "Kolfe Keranio",
    Town: "Bethel",
    Floors: "11th",
    Accommodation: "Rent",
    Price: "50000",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    Type: "Condominium",
    Total_Area: "300",
    Built_in_Area: "300",
    State: "Addis Ababa",
    City: "Kirkos",
    Town: "Gotera",
    Floors: "7th",
    Accommodation: "Sale",
    Price: "25000000",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    Type: "Condominium",
    Total_Area: "360",
    Built_in_Area: "360",
    State: "Addis Ababa",
    City: "Bole",
    Town: "Rwanda",
    Floors: "5th",
    Accommodation: "Sale",
    Price: "35000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    Type: "Personal home",
    Total_Area: "210",
    Built_in_Area: "190",
    State: "DireDawa",
    City: "Kezira",
    Town: "Kafira market",
    Floors: "Villa",
    Accommodation: "Rent",
    Price: "25000",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    Type: "Condominium",
    Total_Area: "120",
    Built_in_Area: "120",
    State: "Addis Ababa",
    City: "Yeka",
    Town: "Ayat",
    Floors: "4th",
    Accommodation: "Sale",
    Price: "4000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    Type: "Apartment",
    Total_Area: "250",
    Built_in_Area: "250",
    State: "Addis Ababa",
    City: "Addis-ketema",
    Town: "Teklehaymanot",
    Floors: "4th",
    Accommodation: "Rent",
    Price: "10000",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    Type: "Personal home",
    Total_Area: "150",
    Built_in_Area: "110",
    State: "Amhara",
    City: "Gojam",
    Town: "Bahirdar",
    Floors: "G+2",
    Accommodation: "Rent",
    Price: "13000",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    Type: "Apartment",
    Total_Area: "120",
    Built_in_Area: "120",
    State: "Oromia",
    City: "Guji",
    Town: "Nagele",
    Floors: "8th",
    Accommodation: "Sale",
    Price: "2000000",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    Type: "Apartment",
    Total_Area: "400",
    Built_in_Area: "400",
    State: "Addis Ababa",
    City: "Kirkos",
    Town: "Sarbet",
    Floors: "12th",
    Accommodation: "Sale",
    Price: "40000000",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    Type: "Condominium",
    Total_Area: "205",
    Built_in_Area: "205",
    State: "Tigray",
    City: "Mekelle",
    Town: "Ayder",
    Floors: "8th",
    Accommodation: "Rent",
    Price: "12000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    Type: "Personal home",
    Total_Area: "180",
    Built_in_Area: "120",
    State: "Tigray",
    City: "Eastern zone",
    Town: "Adigrat",
    Floors: "Villa",
    Accommodation: "Sale",
    Price: "8000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    Type: "Personal home",
    Total_Area: "180",
    Built_in_Area: "150",
    State: "Addis Ababa",
    City: "Addis Ketema",
    Town: "Ched tera",
    Floors: "Villa",
    Accommodation: "Sale",
    Price: "7000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    Type: "Apartment",
    Total_Area: "200",
    Built_in_Area: "200",
    State: "Addis Ababa",
    City: "Bole",
    Town: "Urael",
    Floors: "4th",
    Accommodation: "Sale",
    Price: "10000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    Type: "Condominium",
    Total_Area: "120",
    Built_in_Area: "120",
    State: "Addis Ababa",
    City: "Nefas-silk",
    Town: "Jemo 1",
    Floors: "8th",
    Accommodation: "Sale",
    Price: "3500000",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    Type: "Apartment",
    Total_Area: "200",
    Built_in_Area: "200",
    State: "Sidama",
    City: "Hawassa",
    Town: "Hayk dar",
    Floors: "6th",
    Accommodation: "Sale",
    Price: "8000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    Type: "Apartment",
    Total_Area: "410",
    Built_in_Area: "410",
    State: "Addis Ababa",
    City: "Kolfe-Keranio",
    Town: "Alembank",
    Floors: "6th",
    Accommodation: "Rent",
    Price: "50000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    Type: "Personal home",
    Total_Area: "280",
    Built_in_Area: "200",
    State: "Addis Ababa",
    City: "Nifas-silk",
    Town: "Lafto",
    Floors: "G+5",
    Accommodation: "Sale",
    Price: "25000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    Type: "Condominium",
    Total_Area: "200",
    Built_in_Area: "200",
    State: "Addis Ababa",
    City: "Gulele",
    Town: "Kechene medhanialem",
    Floors: "3rd",
    Accommodation: "Rent",
    Price: "10000",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    Type: "Personal home",
    Total_Area: "205",
    Built_in_Area: "150",
    State: "Amhara",
    City: "Gondar",
    Town: "Piassa",
    Floors: "G+3",
    Accommodation: "Sale",
    Price: "25000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    Type: "Condominium",
    Total_Area: "350",
    Built_in_Area: "350",
    State: "Addis Ababa",
    City: "Akaky Kaliti",
    Town: "Kaliti",
    Floors: "4th",
    Accommodation: "Rent",
    Price: "45000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    Type: "Apartment",
    Total_Area: "380",
    Built_in_Area: "380",
    State: "Addis Ababa",
    City: "Addis Ketema",
    Town: "American Gebi",
    Floors: "6th",
    Accommodation: "Sale",
    Price: "45000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    Type: "Apartment",
    Total_Area: "400",
    Built_in_Area: "400",
    State: "Addis Ababa",
    City: "Lideta",
    Town: "Abenet",
    Floors: "5th",
    Accommodation: "Rent",
    Price: "38000",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    Type: "Apartment",
    Total_Area: "260",
    Built_in_Area: "260",
    State: "Addis Ababa",
    City: "Yeka",
    Town: "Kotebe",
    Floors: "5th",
    Accommodation: "Rent",
    Price: "15000",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    Type: "Personal home",
    Total_Area: "140",
    Built_in_Area: "120",
    State: "Debub",
    City: "Gurage",
    Town: "Welkite",
    Floors: "Villa",
    Accommodation: "Rent",
    Price: "5000",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    Type: "Apartment",
    Total_Area: "200",
    Built_in_Area: "200",
    State: "Addis Ababa",
    City: "Kirkos",
    Town: "Kera",
    Floors: "G+1",
    Accommodation: "Sale",
    Price: "15000000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    Type: "Personal home",
    Total_Area: "450",
    Built_in_Area: "350",
    State: "Addis Ababa",
    City: "Gulele",
    Town: "Addisu Gebeya",
    Floors: "Villa",
    Accommodation: "Rent",
    Price: "28000",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    Type: "Apartment",
    Total_Area: "500",
    Built_in_Area: "500",
    State: "Addis Ababa",
    City: "Yeka",
    Town: "Yeka Abado",
    Floors: "12th",
    Accommodation: "Rent",
    Price: "55000",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    Type: "Personal home",
    Total_Area: "120",
    Built_in_Area: "100",
    State: "Oromia",
    City: "Arsi",
    Town: "Asela",
    Floors: "Villa",
    Accommodation: "Rent",
    Price: "4000",
  },
];

export default data;
